name: todos_api
description: The interface and models for an API providing access to todos.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  equatable: ^2.0.7
  json_annotation: ^4.8.1
  meta: ^1.17.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  test: ^1.26.2
