name: movie_list
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^10.0.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  retrofit_generator: ^9.2.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - .env
