# This project is developed and tested with Flutter 3.29.2
# You do NOT need FVM to run it. Please use Flutter 3.29.2 for best compatibility.

name: products
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.29.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  injectable: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.1.0
  build_runner: ^2.4.0
  auto_route: ^5.0.0
  auto_route_generator: ^5.0.0
  # bloc_test: ^9.0.0

flutter:
  uses-material-design: true

