name: Flutter Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Run unit tests
      run: flutter test

    - name: Run integration tests
      run: flutter test integration_test

    - name: Run E2E tests
      run: flutter drive --target=test_driver/app.dart