name: bloc_examples
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  auto_route: ^10.0.1
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1
  test: ^1.25.15
  bloc_test: ^10.0.0
  bloc_lint: ^0.2.0-dev
  integration_test:
    sdk: flutter
  
flutter:
  uses-material-design: true