name: Flutter CI

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install FVM
      run: |
        pub global activate fvm

    - name: Set up Flutter using FVM
      run: |
        fvm install 3.29.2
        fvm use 3.29.2

    - name: Install dependencies for bloc_examples
      run: |
        cd bloc_examples
        fvm flutter pub get

    - name: Run tests for bloc_examples
      run: |
        cd bloc_examples
        fvm flutter test

    - name: Install dependencies for movie_list
      run: |
        cd movie_list
        fvm flutter pub get

    - name: Run tests for movie_list
      run: |
        cd movie_list
        fvm flutter test