name: Flutter CI

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'

    - name: Install dependencies for bloc_examples
      run: |
        cd bloc_examples
        flutter pub get

    - name: Run tests for bloc_examples
      run: |
        cd bloc_examples
        flutter test

    - name: Install dependencies for movie_list
      run: |
        cd movie_list
        flutter pub get

    - name: Run tests for movie_list
      run: |
        cd movie_list
        flutter test